### ISSUE TITLE
Compilation error: build_task() is not existent

### ISSUE THREAD

**Issue by alexandru0-dev** [bagel897/rustdrop#2]
First of all, great project! I was looking around and found this project and I was interested.

### Compilation error:
 ```
 no method named `build_task` found for struct `JoinSet` in the current scope
  --> rustdrop_core/src/runner/application.rs:29:34
  ```
 
### Workaround:
I solved temporarily just by commenting the lines 34-35 in `application.rs`
 
### Possible solution to spot errors like these:
Using `GitHub Actions` probably can help spot compilation error or test fails. I can contribute to it if u would like to.
 
 I also have other things that I've encountered so I'm going to make other issues for those.

**Comment by bagel897** [comment]
You need to compile with tokio unstable
